server:
  port: 8080

todo-service:
  port: 8081

spring:
  ai:
    mcp:
      server:
        name: todo-mcp-server
        protocol: streamable
        version: 1.0.0
        stdio: false
        type: sync